spring:
  application:
    name: eureka-server
#  profiles:
#    active: pro
server:
  port: 8761
#  profiles: pro
  boot:
    admin:
      client:
        url: http://127.0.0.1:7086
        instance:
          prefer-ip: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 3000
  instance:
    hostname: 127.0.0.1 #内网ip
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 3
    prefer-ip-address: true
    instance-id : 127.0.0.1:${spring.application.name}:${server.port}:@project.version@
    status-page-url: http://127.0.0.1:8761/swagger-ui.html
  client:
    register-with-eureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka